version: 2
jobs:
  hello_world:
    steps:
      - run: echo "Hello World"
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "I'm Build"
workflows:
  version: 2
  schedule_build:
    triggers:
      - schedules:
        cron: "10 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - hello_world

